import tkinter as tk
def click(value):
    current = entry.get()
    entry.delete(0, tk.END)
    entry.insert(0, current + value)
def evaluate():
    try:
        result = eval(entry.get())
        entry.delete(0, tk.END)
        entry.insert(0, str(result))
    except:
        entry.delete(0, tk.END)
        entry.insert(0, "Error")

def clear():
    entry.delete(0, tk.END)
root = tk.Tk()
root.title("Simple Calculator")
root.geometry("500x600")
root.configure(bg="#384047")  
entry = tk.Entry(root, font=("Calibri", 20), width=16, borderwidth=2, relief="solid", bg="#425c44", fg="white")
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=20)

button = tk.Button(root, text="=", width=10, height=3, font=("Calibri", 14), bg="#105c13", fg="white",command=evaluate)
button.grid(row=4, column=3, padx=5, pady=5)
button1=tk.Button(root,text="1" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("1"))
button1.grid(row=3, column=0, padx=5, pady=5)
button2=tk.Button(root,text="2" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("2"))
button2.grid(row=3, column=1, padx=5, pady=5)
button3=tk.Button(root,text="3" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("3"))
button3.grid(row=3, column=2, padx=5, pady=5)
button4=tk.Button(root,text="4" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("4"))
button4.grid(row=2, column=0, padx=5, pady=5)
button5=tk.Button(root,text="5" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("5"))
button5.grid(row=2, column=1, padx=5, pady=5)
button6=tk.Button(root,text="6" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("6"))
button6.grid(row=2, column=2, padx=5, pady=5)
button7=tk.Button(root,text="7" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("7"))
button7.grid(row=1, column=0, padx=5, pady=5)
button8=tk.Button(root,text="8" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("8"))
button8.grid(row=1, column=1, padx=5, pady=5)
button9=tk.Button(root,text="9" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("9"))
button9.grid(row=1, column=2, padx=5, pady=5)
button0=tk.Button(root,text="0" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("0"))
button0.grid(row=4, column=0, padx=5, pady=5)
dot=tk.Button(root,text="." ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("."))
dot.grid(row=4, column=1, padx=5, pady=5)
add=tk.Button(root,text="+" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("+"))
add.grid(row=4, column=2, padx=5, pady=5)
sub=tk.Button(root,text="-" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("-"))
sub.grid(row=3, column=3, padx=5, pady=5)
mul=tk.Button(root,text="*" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("*"))
mul.grid(row=2, column=3, padx=5, pady=5)
div=tk.Button(root,text="/" ,width=10, height=3, font=("Calibri", 14), bg="#808080", fg="white",command= lambda:click("/"))
div.grid(row=1, column=3, padx=5, pady=5)
c = tk.Button(root, text="C", width=10, height=3, font=("Calibri", 14), bg="#FF5733", fg="white", command=clear)
c.grid(row=5, column=0, columnspan=2, padx=5, pady=5)
quitbt = tk.Button(root, text="Quit", width=10, height=3, font=("Calibri", 14), bg="#333333", fg="white", command=root.quit)
quitbt.grid(row=5, column=2, columnspan=2, padx=5, pady=5)
root.mainloop()
